# Generated by Django 4.2.4 on 2023-08-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('university', models.CharField(max_length=50)),
                ('major', models.CharField(max_length=50)),
                ('essay1', models.TextField()),
                ('essay2', models.TextField()),
                ('essay3', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='middle_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
