# Generated by Django 4.2.4 on 2023-08-08 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_mentor_alter_student_middle_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mentor',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
